// SOLVE THESE THREE CHALLENGES IF YOU DARE!
// 1. WHEN YOUR MOUSE IS OVER THE MORBIUS (GREATEST MOVIE EVER BTW) IMAGE
// YOU SHOULD ALERT THE USER THAT IT IS INDEED A MOVIE.
// 2. WHEN YOU CLICK THE DIE ON THE SCREEN YOU GET A RANDOM NEW DIE
// FOR THIS CHALLENGE USE THE IMAGES IN THE IMAGE FOLDER (HINT NOTICE THE NAMES OF THE IMAGE)
// 3. APPLY THE FUNCTIONALITY DO THE LAST SECTION AND MAKE IT SO WE CAN DELETE CARDS.